<script>
  import Column from "$lib/hl-components/dashboardx/grid/GridColumn_Dash.svelte";
  import Insert from "$lib/hl-components/dashboardx/grid/GridInsert_Dash.svelte";
  import Item from "$lib/hl-components/dashboardx/grid/GridItem_Dash.svelte";
  import Row from "$lib/hl-components/dashboardx/grid/GridRow_Dash.svelte";
  import Grid from "$lib/hl-components/dashboardx/grid/GridTemplate_Dash.svelte";

  const propertyData = {
    id: "c411a2bd-c856-433f-babe-6294b6c29e35",
    name: "FLAT in BS33NQ",
    reference: "AICO_HOMELINK_DEMO_Mitch_flat",
    displayReference: "Mitch_flat",
    landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
    landlordReference: "AICO_HOMELINK_DEMO",
    landlordParentReference: null,
    landlordName: "Aico HomeLINK Demo",
    parentPropertyDisplayReference: null,
    parentPropertyReference: null,
    parentPropertyId: null,
    typeId: "FLAT",
    typeName: "Flat",
    statusId: "ACTIVE",
    constructionTypeId: "TRA",
    heatingTypeId: "ELEC",
    heatingTypeName: "Electric",
    constructionTypeName: "Traditional",
    constructionDate: "2000-01-01T00:00:00.000Z",
    createdAt: "2022-01-26T11:39:11.127Z",
    updatedAt: "2023-01-23T08:08:13.571Z",
    parentId: null,
    propertyFloorId: "6th",
    propertyFloorName: "6th Floor",
    buildingTypeId: "BLOCK",
    buildingTypeName: "Tower Block",
    designationId: "DOMESTIC",
    designationName: "domestic",
    deviceTypes: {
      hasCo2Device: false,
      hasWeatherDevice: true,
      hasBoilerDevice: false,
      hasCoAlarmDevice: true,
      hasEiAccessoryDevice: false,
      hasElectricityDevice: false,
      hasEnvCo2Device: true,
      hasEnvDevice: false,
      hasFireAlarmDevice: true,
      hasFireCoAlarmDevice: false,
      hasGatewayDevice: true,
      hasSmartMeterElecDevice: true,
      hasSmartMeterGasDevice: false,
      hasSmartMeterGasElecDevice: false,
    },
    address: {
      uprn: "Mitch_flat_017387",
      flatIdentifier: null,
      nameNumber: "611 Airpoint",
      street: "Skypark Road",
      locality: "",
      county: "",
      city: "Bristol",
      postcode: "BS33NQ",
      country: "GB",
      displayAddressFull: "611 Airpoint Skypark Road  Bristol  BS33NQ GB",
      displayAddressSms: "611 Airpoint BS33NQ",
      propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
      propertyReference: "AICO_HOMELINK_DEMO_Mitch_flat",
      confidenceId: "FULL",
    },
    geo: {
      latitude: 51.4375366,
      longitude: -2.6027804,
      pitch: 8,
      heading: 0,
      zoom: 14,
      propertyImageUrl: null,
    },
    statistics: {
      activeAlerts: 0,
      eiSystemLastSeen: "2023-10-12T14:48:57.341Z",
      eiGatewayStatus: "Poor",
      eiDeviceStatus: "Good",
    },
    insights: [
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "15862be3-7f04-11ec-8066-0a627a563cd4",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: 40.546,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: null,
        resultComponents: [],
      },
      {
        insightDefinitionId: "COLDHOMES",
        insightDefinitionName: "Cold Home Risk",
        id: "158640f7-7f04-11ec-8066-0a627a563cd4",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: 0.0282,
        modelVersionId: "B_COLDHOMES-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: null,
        resultComponents: [],
      },
      {
        insightDefinitionId: "EXCESSHEAT",
        insightDefinitionName: "Excess heat risk",
        id: "1586651a-7f04-11ec-8066-0a627a563cd4",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: 0.0437,
        modelVersionId: "B_EXCESSHEAT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: null,
        resultComponents: [],
      },
      {
        insightDefinitionId: "AIRQUALITY",
        insightDefinitionName: "Indoor Air Quality Risk",
        id: "26ec860d-3820-4ec7-bf3d-525804f4c047",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: 36.6063,
        modelVersionId: "B_AIRQUALITY-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: null,
        resultComponents: [
          {
            insightId: "26ec860d-3820-4ec7-bf3d-525804f4c047",
            typeId: "airquality.co2.harm",
            value: 20.3165,
            name: "IAQ Harm",
            description:
              "Harm risk from long exposure to CO2 at different levels",
          },
        ],
      },
      {
        insightDefinitionId: "VENTILATION",
        insightDefinitionName: "Draught Risk",
        id: "389b0aa8-3418-11ef-90d0-0a6c788a5c82",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "PENDING",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: null,
        modelVersionId: "A_VENTILATION-6",
        calculatedAt: null,
        location: null,
      },
      {
        insightDefinitionId: "ABANDONMENT",
        insightDefinitionName: "Void Risk",
        id: "9624cd4c-fcbe-11ec-9aed-0a1d39029b24",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: 0,
        modelVersionId: "B_ABANDONMENT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: null,
        resultComponents: [],
      },
      {
        insightDefinitionId: "MOULD",
        insightDefinitionName: "Damp and Mould Risk",
        id: "9675d176-fcbe-11ec-9aed-0a1d39029b24",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: 63.4085,
        modelVersionId: "B_DAMPMOULD-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: null,
        resultComponents: [],
      },
      {
        insightDefinitionId: "HEATLOSS",
        insightDefinitionName: "Heat Loss Risk",
        id: "fc21296a-d8c4-11ed-9682-0a43f1649be6",
        statusId: "ACTIVE",
        lastSyncDateTime: "2024-06-28T02:00:00.000Z",
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: null,
        locationNickname: null,
        locationName: null,
        value: 24.4131,
        modelVersionId: "A_HEATLOSS-3",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: null,
        resultComponents: [
          {
            insightId: "fc21296a-d8c4-11ed-9682-0a43f1649be6",
            typeId:
              "heatloss.halflife.temperature.mean.percentile40:percentile60",
            value: 5598.0588,
            name: "Heatloss - Mean of Central perecentiles",
            description:
              "Heatloss based on the mean of percentiles 40 through 60 of temperature decays",
          },
          {
            insightId: "fc21296a-d8c4-11ed-9682-0a43f1649be6",
            typeId: "heatloss.risk.scaled",
            value: 24.4131,
            name: "Heat Loss Risk - Scaled",
            description:
              "Heat Loss risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
    ],
    roomInsights: [
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "08311924-4204-4df0-88e8-2fe9b56eda7a",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM4",
        locationNickname: null,
        locationName: "Bedroom 4",
        value: 19.8113,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2023-07-25T02:00:00.000Z",
        location: "Bedroom 4",
        resultComponents: [],
      },
      {
        insightDefinitionId: "HEATLOSS",
        insightDefinitionName: "Heat Loss Risk",
        id: "16c73cdb-2a27-4453-9ff9-0f3709759140",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "STUDY",
        locationNickname: null,
        locationName: "Study",
        value: 8.3713,
        modelVersionId: "A_HEATLOSS-3",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Study",
        resultComponents: [
          {
            insightId: "16c73cdb-2a27-4453-9ff9-0f3709759140",
            typeId:
              "heatloss.halflife.temperature.mean.percentile40:percentile60",
            value: 11283.376,
            name: "Heatloss - Mean of Central perecentiles",
            description:
              "Heatloss based on the mean of percentiles 40 through 60 of temperature decays",
          },
          {
            insightId: "16c73cdb-2a27-4453-9ff9-0f3709759140",
            typeId: "heatloss.risk.percentile",
            value: 85.4385,
            name: "Heat Loss - Percentile",
            description:
              "Percentile location of Heat Loss risk relative to known portfolio distribution",
          },
          {
            insightId: "16c73cdb-2a27-4453-9ff9-0f3709759140",
            typeId: "heatloss.risk.scaled",
            value: 8.3713,
            name: "Heat Loss Risk - Scaled",
            description:
              "Heat Loss risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
      {
        insightDefinitionId: "MOULD",
        insightDefinitionName: "Damp and Mould Risk",
        id: "25ccf820-2511-471b-8bd4-beb492554c51",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "STUDY",
        locationNickname: null,
        locationName: "Study",
        value: 22.3057,
        modelVersionId: "B_DAMPMOULD-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Study",
        resultComponents: [
          {
            insightId: "25ccf820-2511-471b-8bd4-beb492554c51",
            typeId: "damp.wall.humidity.baseline.normalised",
            value: 5.7356,
            name: "Baseline Humidity Score",
            description: "Average of minimums from the estimated wall humidity",
          },
          {
            insightId: "25ccf820-2511-471b-8bd4-beb492554c51",
            typeId: "heatloss.halflife.temperature.normalised",
            value: 1.4264,
            name: "Heat Loss Score",
            description:
              "Normalised score of heat loss estimation based on temperature half life median decay",
          },
          {
            insightId: "25ccf820-2511-471b-8bd4-beb492554c51",
            typeId: "ventilation.halflife.absolutehumidity.median.normalised",
            value: 6.8821,
            name: "Ventilation Inefficiency from Humidity Score",
            description: "Ventilation based on humidity half life median decay",
          },
          {
            insightId: "25ccf820-2511-471b-8bd4-beb492554c51",
            typeId: "spike.humidity.pattern",
            value: 1.6534,
            name: "Peak Humidity Score",
            description: "Absolute humidity spike pattern score",
          },
          {
            insightId: "25ccf820-2511-471b-8bd4-beb492554c51",
            typeId: "heating.temperature.consistency.normalised",
            value: 1.6485,
            name: "Heating Consistency Score",
            description: "Heating consistency score",
          },
          {
            insightId: "25ccf820-2511-471b-8bd4-beb492554c51",
            typeId:
              "ventilation.halflife.absolutehumidity.aboveaverage.normalised",
            value: 2.5952,
            name: "Potential Ventilation Score",
            description:
              "Unrealised ventilation based on average absolute humidity decays which are above median",
          },
          {
            insightId: "25ccf820-2511-471b-8bd4-beb492554c51",
            typeId: "mould.risk.scaled",
            value: 22.3057,
            name: "Mould Risk - Scaled",
            description:
              "Mould Risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
      {
        insightDefinitionId: "COLDHOMES",
        insightDefinitionName: "Cold Home Risk",
        id: "2d823185-9073-4e5b-b1f0-390001e5b279",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM1",
        locationNickname: null,
        locationName: "Bedroom 1",
        value: 0.0282,
        modelVersionId: "B_COLDHOMES-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bedroom 1",
        resultComponents: [],
      },
      {
        insightDefinitionId: "COLDHOMES",
        insightDefinitionName: "Cold Home Risk",
        id: "3b9070ea-fbb3-4160-9827-6b850b190f40",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BATHROOM",
        locationNickname: null,
        locationName: "Bathroom",
        value: 0.0282,
        modelVersionId: "B_COLDHOMES-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bathroom",
        resultComponents: [],
      },
      {
        insightDefinitionId: "ABANDONMENT",
        insightDefinitionName: "Void Risk",
        id: "4a31cbb2-fd1b-41af-9b7b-56fa4bc8e6c0",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "STUDY",
        locationNickname: null,
        locationName: "Study",
        value: 0,
        modelVersionId: "B_ABANDONMENT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Study",
        resultComponents: [],
      },
      {
        insightDefinitionId: "HEATLOSS",
        insightDefinitionName: "Heat Loss Risk",
        id: "4c33ef9a-db67-461d-b33f-a5681cfd9bb2",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "LIVINGROOM",
        locationNickname: null,
        locationName: "Living Room",
        value: 24.4131,
        modelVersionId: "A_HEATLOSS-3",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Living Room",
        resultComponents: [
          {
            insightId: "4c33ef9a-db67-461d-b33f-a5681cfd9bb2",
            typeId:
              "heatloss.halflife.temperature.mean.percentile40:percentile60",
            value: 5598.0588,
            name: "Heatloss - Mean of Central perecentiles",
            description:
              "Heatloss based on the mean of percentiles 40 through 60 of temperature decays",
          },
          {
            insightId: "4c33ef9a-db67-461d-b33f-a5681cfd9bb2",
            typeId: "heatloss.risk.percentile",
            value: 59.4507,
            name: "Heat Loss - Percentile",
            description:
              "Percentile location of Heat Loss risk relative to known portfolio distribution",
          },
          {
            insightId: "4c33ef9a-db67-461d-b33f-a5681cfd9bb2",
            typeId: "heatloss.risk.scaled",
            value: 24.4131,
            name: "Heat Loss Risk - Scaled",
            description:
              "Heat Loss risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "521b14d9-6d13-4ac7-a1d4-fec165fc0c8d",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM3",
        locationNickname: null,
        locationName: "Bedroom 3",
        value: 26.4985,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2023-07-25T02:00:00.000Z",
        location: "Bedroom 3",
        resultComponents: [],
      },
      {
        insightDefinitionId: "ABANDONMENT",
        insightDefinitionName: "Void Risk",
        id: "62669cc9-8891-410c-b92d-babb0b9408d2",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM1",
        locationNickname: null,
        locationName: "Bedroom 1",
        value: 0,
        modelVersionId: "B_ABANDONMENT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bedroom 1",
        resultComponents: [],
      },
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "633712b5-6625-4e1e-91ee-f87bbaef0436",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM2",
        locationNickname: null,
        locationName: "Bedroom 2",
        value: 32.8665,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2023-07-25T02:00:00.000Z",
        location: "Bedroom 2",
        resultComponents: [],
      },
      {
        insightDefinitionId: "COLDHOMES",
        insightDefinitionName: "Cold Home Risk",
        id: "63ac3951-872c-4980-a5a8-a9a9080c87fb",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "LIVINGROOM",
        locationNickname: null,
        locationName: "Living Room",
        value: 0.0282,
        modelVersionId: "B_COLDHOMES-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Living Room",
        resultComponents: [],
      },
      {
        insightDefinitionId: "AIRQUALITY",
        insightDefinitionName: "Indoor Air Quality Risk",
        id: "6471b963-8bcb-46aa-a997-9e7cfe7140d8",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BATHROOM",
        locationNickname: null,
        locationName: "Bathroom",
        value: 4.3054,
        modelVersionId: "B_AIRQUALITY-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bathroom",
        resultComponents: [
          {
            insightId: "6471b963-8bcb-46aa-a997-9e7cfe7140d8",
            typeId: "airquality.co2.harm",
            value: 2.3895,
            name: "IAQ Harm",
            description:
              "Harm risk from long exposure to CO2 at different levels",
          },
        ],
      },
      {
        insightDefinitionId: "AIRQUALITY",
        insightDefinitionName: "Indoor Air Quality Risk",
        id: "7dafb3d5-289a-4e69-a1d2-067bcae3130d",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "STUDY",
        locationNickname: null,
        locationName: "Study",
        value: 10.9869,
        modelVersionId: "B_AIRQUALITY-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Study",
        resultComponents: [
          {
            insightId: "7dafb3d5-289a-4e69-a1d2-067bcae3130d",
            typeId: "airquality.co2.harm",
            value: 6.0977,
            name: "IAQ Harm",
            description:
              "Harm risk from long exposure to CO2 at different levels",
          },
        ],
      },
      {
        insightDefinitionId: "AIRQUALITY",
        insightDefinitionName: "Indoor Air Quality Risk",
        id: "844dd21f-0302-4b5d-b35f-013e5df10cb3",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: "BEDROOM1",
        locationNickname: null,
        locationName: "Bedroom 1",
        value: 36.6063,
        modelVersionId: "B_AIRQUALITY-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bedroom 1",
        resultComponents: [
          {
            insightId: "844dd21f-0302-4b5d-b35f-013e5df10cb3",
            typeId: "airquality.co2.harm",
            value: 20.3165,
            name: "IAQ Harm",
            description:
              "Harm risk from long exposure to CO2 at different levels",
          },
        ],
      },
      {
        insightDefinitionId: "EXCESSHEAT",
        insightDefinitionName: "Excess heat risk",
        id: "933b5e69-ab31-474b-bdb9-183ff6647994",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BATHROOM",
        locationNickname: null,
        locationName: "Bathroom",
        value: 0.0437,
        modelVersionId: "B_EXCESSHEAT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bathroom",
        resultComponents: [],
      },
      {
        insightDefinitionId: "EXCESSHEAT",
        insightDefinitionName: "Excess heat risk",
        id: "94091626-e1d0-4090-a94e-da437b4c04e3",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "STUDY",
        locationNickname: null,
        locationName: "Study",
        value: 0,
        modelVersionId: "B_EXCESSHEAT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Study",
        resultComponents: [],
      },
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "98120211-3aa8-4438-8291-6faf99c73d78",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "SITTINGROOM2",
        locationNickname: null,
        locationName: "Sitting Room 2",
        value: 19.2898,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2023-07-24T02:00:00.000Z",
        location: "Sitting Room 2",
        resultComponents: [],
      },
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "9e3d634f-bd5a-4a77-8945-a29f6b206f65",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: "SITTINGROOM1",
        locationNickname: null,
        locationName: "Sitting Room 1",
        value: 46.3773,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2023-07-24T02:00:00.000Z",
        location: "Sitting Room 1",
        resultComponents: [],
      },
      {
        insightDefinitionId: "AIRQUALITY",
        insightDefinitionName: "Indoor Air Quality Risk",
        id: "b8a7a3da-059b-4ab4-89c4-a9517fb0a579",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "LIVINGROOM",
        locationNickname: null,
        locationName: "Living Room",
        value: 3.2065,
        modelVersionId: "B_AIRQUALITY-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Living Room",
        resultComponents: [
          {
            insightId: "b8a7a3da-059b-4ab4-89c4-a9517fb0a579",
            typeId: "airquality.co2.harm",
            value: 1.7796,
            name: "IAQ Harm",
            description:
              "Harm risk from long exposure to CO2 at different levels",
          },
        ],
      },
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "c0eae353-8ce9-42af-ad3d-2497bf55b9f3",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: "BEDROOM1",
        locationNickname: null,
        locationName: "Bedroom 1",
        value: 40.546,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bedroom 1",
        resultComponents: [],
      },
      {
        insightDefinitionId: "MOULD",
        insightDefinitionName: "Damp and Mould Risk",
        id: "c6bc2529-307c-46e9-9779-3314921d82df",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: "BATHROOM",
        locationNickname: null,
        locationName: "Bathroom",
        value: 63.4085,
        modelVersionId: "B_DAMPMOULD-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bathroom",
        resultComponents: [
          {
            insightId: "c6bc2529-307c-46e9-9779-3314921d82df",
            typeId: "damp.wall.humidity.baseline.normalised",
            value: 5.7912,
            name: "Baseline Humidity Score",
            description: "Average of minimums from the estimated wall humidity",
          },
          {
            insightId: "c6bc2529-307c-46e9-9779-3314921d82df",
            typeId: "heatloss.halflife.temperature.normalised",
            value: 3.5572,
            name: "Heat Loss Score",
            description:
              "Normalised score of heat loss estimation based on temperature half life median decay",
          },
          {
            insightId: "c6bc2529-307c-46e9-9779-3314921d82df",
            typeId: "ventilation.halflife.absolutehumidity.median.normalised",
            value: 3.4103,
            name: "Ventilation Inefficiency from Humidity Score",
            description: "Ventilation based on humidity half life median decay",
          },
          {
            insightId: "c6bc2529-307c-46e9-9779-3314921d82df",
            typeId: "spike.humidity.pattern",
            value: 10,
            name: "Peak Humidity Score",
            description: "Absolute humidity spike pattern score",
          },
          {
            insightId: "c6bc2529-307c-46e9-9779-3314921d82df",
            typeId: "heating.temperature.consistency.normalised",
            value: 0.8474,
            name: "Heating Consistency Score",
            description: "Heating consistency score",
          },
          {
            insightId: "c6bc2529-307c-46e9-9779-3314921d82df",
            typeId:
              "ventilation.halflife.absolutehumidity.aboveaverage.normalised",
            value: 3.7903,
            name: "Potential Ventilation Score",
            description:
              "Unrealised ventilation based on average absolute humidity decays which are above median",
          },
          {
            insightId: "c6bc2529-307c-46e9-9779-3314921d82df",
            typeId: "mould.risk.scaled",
            value: 63.4085,
            name: "Mould Risk - Scaled",
            description:
              "Mould Risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
      {
        insightDefinitionId: "HEATLOSS",
        insightDefinitionName: "Heat Loss Risk",
        id: "cdeea94a-af4f-4e45-b658-38324c84164d",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM1",
        locationNickname: null,
        locationName: "Bedroom 1",
        value: 16.122,
        modelVersionId: "A_HEATLOSS-3",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bedroom 1",
        resultComponents: [
          {
            insightId: "cdeea94a-af4f-4e45-b658-38324c84164d",
            typeId:
              "heatloss.halflife.temperature.mean.percentile40:percentile60",
            value: 7409.342,
            name: "Heatloss - Mean of Central perecentiles",
            description:
              "Heatloss based on the mean of percentiles 40 through 60 of temperature decays",
          },
          {
            insightId: "cdeea94a-af4f-4e45-b658-38324c84164d",
            typeId: "heatloss.risk.percentile",
            value: 72.8824,
            name: "Heat Loss - Percentile",
            description:
              "Percentile location of Heat Loss risk relative to known portfolio distribution",
          },
          {
            insightId: "cdeea94a-af4f-4e45-b658-38324c84164d",
            typeId: "heatloss.risk.scaled",
            value: 16.122,
            name: "Heat Loss Risk - Scaled",
            description:
              "Heat Loss risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
      {
        insightDefinitionId: "ABANDONMENT",
        insightDefinitionName: "Void Risk",
        id: "db2e428b-e0eb-4fa7-81bc-c553001f5917",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BATHROOM",
        locationNickname: null,
        locationName: "Bathroom",
        value: 0,
        modelVersionId: "B_ABANDONMENT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bathroom",
        resultComponents: [],
      },
      {
        insightDefinitionId: "EXCESSHEAT",
        insightDefinitionName: "Excess heat risk",
        id: "dc8c9dc4-e3a9-4776-9747-48a40f4c5a7c",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM1",
        locationNickname: null,
        locationName: "Bedroom 1",
        value: 0,
        modelVersionId: "B_EXCESSHEAT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bedroom 1",
        resultComponents: [],
      },
      {
        insightDefinitionId: "ABANDONMENT",
        insightDefinitionName: "Void Risk",
        id: "dce5e6ac-39bf-42a0-b485-db83ecb156d6",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "LIVINGROOM",
        locationNickname: null,
        locationName: "Living Room",
        value: 0,
        modelVersionId: "B_ABANDONMENT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Living Room",
        resultComponents: [],
      },
      {
        insightDefinitionId: "EXCESSHEAT",
        insightDefinitionName: "Excess heat risk",
        id: "dfd7cb2e-285f-4fb3-b6ab-0e21bed651d4",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "LIVINGROOM",
        locationNickname: null,
        locationName: "Living Room",
        value: 0,
        modelVersionId: "B_EXCESSHEAT-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Living Room",
        resultComponents: [],
      },
      {
        insightDefinitionId: "HEATLOSS",
        insightDefinitionName: "Heat Loss Risk",
        id: "e44ccbff-4220-4749-ac2c-0e7b9536dbbc",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BATHROOM",
        locationNickname: null,
        locationName: "Bathroom",
        value: 21.9771,
        modelVersionId: "A_HEATLOSS-3",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bathroom",
        resultComponents: [
          {
            insightId: "e44ccbff-4220-4749-ac2c-0e7b9536dbbc",
            typeId:
              "heatloss.halflife.temperature.mean.percentile40:percentile60",
            value: 6033.4703,
            name: "Heatloss - Mean of Central perecentiles",
            description:
              "Heatloss based on the mean of percentiles 40 through 60 of temperature decays",
          },
          {
            insightId: "e44ccbff-4220-4749-ac2c-0e7b9536dbbc",
            typeId: "heatloss.risk.percentile",
            value: 63.3971,
            name: "Heat Loss - Percentile",
            description:
              "Percentile location of Heat Loss risk relative to known portfolio distribution",
          },
          {
            insightId: "e44ccbff-4220-4749-ac2c-0e7b9536dbbc",
            typeId: "heatloss.risk.scaled",
            value: 21.9771,
            name: "Heat Loss Risk - Scaled",
            description:
              "Heat Loss risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
      {
        insightDefinitionId: "COLDHOMES",
        insightDefinitionName: "Cold Home Risk",
        id: "f19c642e-12fc-4062-83df-4656f7928c56",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "STUDY",
        locationNickname: null,
        locationName: "Study",
        value: 0.0282,
        modelVersionId: "B_COLDHOMES-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Study",
        resultComponents: [],
      },
      {
        insightDefinitionId: "MOULD",
        insightDefinitionName: "Damp and Mould Risk",
        id: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "LIVINGROOM",
        locationNickname: null,
        locationName: "Living Room",
        value: 15.8422,
        modelVersionId: "B_DAMPMOULD-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Living Room",
        resultComponents: [
          {
            insightId: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
            typeId: "damp.wall.humidity.baseline.normalised",
            value: 4.5475,
            name: "Baseline Humidity Score",
            description: "Average of minimums from the estimated wall humidity",
          },
          {
            insightId: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
            typeId: "heatloss.halflife.temperature.normalised",
            value: 4.0328,
            name: "Heat Loss Score",
            description:
              "Normalised score of heat loss estimation based on temperature half life median decay",
          },
          {
            insightId: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
            typeId: "ventilation.halflife.absolutehumidity.median.normalised",
            value: 2.7486,
            name: "Ventilation Inefficiency from Humidity Score",
            description: "Ventilation based on humidity half life median decay",
          },
          {
            insightId: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
            typeId: "spike.humidity.pattern",
            value: 3.5489,
            name: "Peak Humidity Score",
            description: "Absolute humidity spike pattern score",
          },
          {
            insightId: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
            typeId: "heating.temperature.consistency.normalised",
            value: 1.4003,
            name: "Heating Consistency Score",
            description: "Heating consistency score",
          },
          {
            insightId: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
            typeId:
              "ventilation.halflife.absolutehumidity.aboveaverage.normalised",
            value: 3.6325,
            name: "Potential Ventilation Score",
            description:
              "Unrealised ventilation based on average absolute humidity decays which are above median",
          },
          {
            insightId: "f21b34bc-a5fa-481f-b167-6e9d39ec9c28",
            typeId: "mould.risk.scaled",
            value: 15.8422,
            name: "Mould Risk - Scaled",
            description:
              "Mould Risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
      {
        insightDefinitionId: "ALLERGENS",
        insightDefinitionName: "Dust Mite Allergens Risk",
        id: "f40e5169-fa86-4f95-981b-673fe6fd24c2",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "MEDIUM",
        locationId: "LIVINGROOM",
        locationNickname: null,
        locationName: "Living Room",
        value: 36.4353,
        modelVersionId: "B_ALLERGENS-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Living Room",
        resultComponents: [],
      },
      {
        insightDefinitionId: "MOULD",
        insightDefinitionName: "Damp and Mould Risk",
        id: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
        statusId: "ACTIVE",
        lastSyncDateTime: null,
        propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
        parentPropertyId: null,
        levelId: "LOW",
        locationId: "BEDROOM1",
        locationNickname: null,
        locationName: "Bedroom 1",
        value: 28.2339,
        modelVersionId: "B_DAMPMOULD-002",
        calculatedAt: "2024-06-28T02:00:00.000Z",
        location: "Bedroom 1",
        resultComponents: [
          {
            insightId: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
            typeId: "damp.wall.humidity.baseline.normalised",
            value: 5.358,
            name: "Baseline Humidity Score",
            description: "Average of minimums from the estimated wall humidity",
          },
          {
            insightId: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
            typeId: "heatloss.halflife.temperature.normalised",
            value: 2.6847,
            name: "Heat Loss Score",
            description:
              "Normalised score of heat loss estimation based on temperature half life median decay",
          },
          {
            insightId: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
            typeId: "ventilation.halflife.absolutehumidity.median.normalised",
            value: 3.0172,
            name: "Ventilation Inefficiency from Humidity Score",
            description: "Ventilation based on humidity half life median decay",
          },
          {
            insightId: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
            typeId: "spike.humidity.pattern",
            value: 2.7791,
            name: "Peak Humidity Score",
            description: "Absolute humidity spike pattern score",
          },
          {
            insightId: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
            typeId: "heating.temperature.consistency.normalised",
            value: 1.0841,
            name: "Heating Consistency Score",
            description: "Heating consistency score",
          },
          {
            insightId: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
            typeId:
              "ventilation.halflife.absolutehumidity.aboveaverage.normalised",
            value: 4.442,
            name: "Potential Ventilation Score",
            description:
              "Unrealised ventilation based on average absolute humidity decays which are above median",
          },
          {
            insightId: "f84602cf-8a4e-46f6-9333-e9a5f739e8f2",
            typeId: "mould.risk.scaled",
            value: 28.2339,
            name: "Mould Risk - Scaled",
            description:
              "Mould Risk scaled to a 0 to 100 range with low risk <33.33333, medium risk < 66.66666 else high risk",
          },
        ],
      },
    ],
    devicesStats: [],
    propertyIdentifiers: [
      {
        key: "aicouprn",
        value: "Mitch_flat_017387",
      },
      {
        key: "aicovpid",
        value: "017387",
      },
      {
        key: "POSTCODE",
        value: "BS33NQ",
      },
    ],
    tags: ["15 ABERCROMBIE STREET", "AICO DEMO", "DAFAS", "HL TEAM"],
  };

  const notes = [
    {
      count: 6,
      raisedDate: "2024-01-15T16:59:14.962Z",
    },
  ];

  const feedData = notes.map((alert) => ({
    title: "Property Note",
    subtitle: "note",
    description: "Notes that have been added to the property",
    status: null,
    date: alert.raisedDate,
    count: alert.count,
    statusColor: "red",
    countColor: "red",
    image: "image",
  }));

  const gerSeverity = (severity) => {
    if (severity === "HIGH") {
      return "red";
    } else if (severity === "MEDIUM") {
      return "orange";
    } else if (severity === "LOW") {
      return "green";
    } else {
      return "grey";
    }
  };
  const risksData = propertyData.insights.map((alert) => ({
    title: null,
    subtitle: alert.insightDefinitionName,
    description: null,
    status: null,
    date: null,
    count: null,
    statusColor: null,
    countColor: null,
    ringLabel: alert.levelId,
    ringColor: gerSeverity(alert.levelId),
    ringTextSize: "0.5rem",
    image: "",
  }));

  const tagData = propertyData.tags.map((tag) => tag);
  const activeAlertTypesCollumns = [
    { title: "", field: "label" },
    { title: "", field: "value" },
  ];

  const details = [
    { label: "Reference", value: propertyData.displayReference },
    { label: "Key", value: propertyData.reference },
    { label: "Dwelling Type", value: propertyData.typeName },
    { label: "Building Type", value: propertyData.buildingTypeName },
    { label: "Floor", value: propertyData.propertyFloorName },
    { label: "Year Build", value: propertyData.constructionDate },
    { label: "Construction Type", value: propertyData.constructionTypeName },

    { label: "HeatingType", value: propertyData.heatingTypeName },
  ];
</script>

<div>
  <Grid>
    <Row>
      <Item>
        <Insert insert="Bar" subtitle="0" title="Monitored Rooms" />
      </Item>
      <Item>
        <Insert insert="Bar" subtitle="0" title="Total Active Alerts" />
      </Item>
      <Item>
        <Insert insert="Bar" subtitle="0" title="Fire & CO Status" />
      </Item>
      <Item>
        <Insert insert="Bar" subtitle="0" title="Gateway Status" />
      </Item>
      <Item>
        <Insert insert="Bar" subtitle="0" title="?" />
      </Item>
    </Row>
    <Row>
      <Column>
        <Item title="Active Alert Types" scroll height={300}>
          <Insert
            insert="Details"
            columns={activeAlertTypesCollumns}
            data={details}
          />
        </Item>
        <Item>
          <Insert insert="Tag" title="tags" data={tagData} />
        </Item>

        <Item title="Risks" scroll height={300}>
          <Insert
            insert="Feed"
            title="title"
            subtitle="subtitle"
            data={risksData}
          />
        </Item>
      </Column>

      <Column>
        <Item>
          <Insert
            insert="Feed"
            title="title"
            subtitle="subtitle"
            data={feedData}
          />
        </Item>
      </Column>

      <Column>
        <Item>
          <Insert insert="Map" title="Location" />
        </Item>
        <Item>
          <Insert insert="Default" title="Streetview" />
        </Item>
      </Column>
    </Row>
  </Grid>
</div>
