<script>
  import Table from "$lib/components/reports/ReportTable.svelte";

  const device = [
    {
      propertyId: "f7c0529a-9944-4ec6-9d9f-09786070ef1b",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_G-R",
      propertyDisplayReference: "15",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "45 Scott Street  DUNDEE DD22AP GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei3016 Optical Alarm",
      modelTypeId: "FIREALARM",
      modelReference: "Ei3016",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: null,
      batteryVoltage: null,
      lastSeenDate: "2022-11-24T14:03:08.000Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Ryan Conway",
      iccid: "",
      id: "00a352b2-9cde-4e73-bb5f-cfd0b8899427",
      name: "Ei3016 Hallway 1",
      serialNumber: "C6FACFF3",
      deviceSeqId: 486,
      virtualId: "31C95C8B-5ED0-431F-AB64-6AB67B688213",
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2022-09-02T14:13:02.344Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2033-05-02T00:00:00.000Z",
      createdAt: "2022-09-02T14:13:08.517Z",
      updatedAt: "2022-10-05T10:45:40.204Z",
      hidden: false,
      modelId: 11,
      deviceId: "00a352b2-9cde-4e73-bb5f-cfd0b8899427",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "31C95C8B-5ED0-431F-AB64-6AB67B688213",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "C6FACFF3",
        },
        {
          key: "VIRTUALID",
          value: "31C95C8B-5ED0-431F-AB64-6AB67B688213",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "G/R_024927",
        },
        {
          key: "aicovpid",
          value: "024927",
        },
        {
          key: "POSTCODE",
          value: "DD22AP",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "FIREALARM",
        modelTypeName: "Fire Alarm",
        modelTypeId: "FIREALARM",
        id: 11,
        name: "Ei3016 Optisch Alarm",
        reference: "Ei3016",
        description: "Ei/Aico Ei3016 Optical Alarm",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 132,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Ei3016 Events",
            scheduleReference: "Ei3016",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: null,
        batteryVoltage: null,
        lastSeenDate: "2022-11-24T14:03:08.000Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Ryan Conway",
        iccid: "",
        age: 787,
        lifePercentage: 81,
      },
      lifetimeMonths: 132,
      locationName: "Hallway 1",
      physicalSerialNumber: "C6FACFF3",
      address: {
        uprn: "G/R_024927",
        flatIdentifier: null,
        nameNumber: "45 Scott Street",
        street: "",
        locality: null,
        county: null,
        city: "DUNDEE",
        postcode: "DD22AP",
        country: "GB",
      },
    },
    {
      propertyId: "add1a247-8274-412b-a6a9-aee5d357ab77",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_TB001",
      propertyDisplayReference: "TB001",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "6 Orchard Bank   Carluke ML85FA GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei3016 Optical Alarm",
      modelTypeId: "FIREALARM",
      modelReference: "Ei3016",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -59,
      batteryVoltage: null,
      lastSeenDate: "2023-06-11T17:39:24.883Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "tony.boyle@aico.co.uk",
      iccid: "",
      id: "00b86d21-ed03-498f-8a07-439093da7b63",
      name: "Ei3016 Hallway 1",
      serialNumber: "E7E5D7F3",
      deviceSeqId: 546,
      virtualId: "9E508AB7-7C03-4494-B00B-D37FF2EB0314",
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2022-01-05T17:47:21.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2031-05-25T00:00:00.000Z",
      createdAt: "2022-01-05T18:02:38.789Z",
      updatedAt: "2022-10-05T10:45:48.593Z",
      hidden: false,
      modelId: 11,
      deviceId: "00b86d21-ed03-498f-8a07-439093da7b63",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "9E508AB7-7C03-4494-B00B-D37FF2EB0314",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "E7E5D7F3",
        },
        {
          key: "VIRTUALID",
          value: "9E508AB7-7C03-4494-B00B-D37FF2EB0314",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "TB001_016474",
        },
        {
          key: "aicovpid",
          value: "016474",
        },
        {
          key: "POSTCODE",
          value: "ML85FA",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "FIREALARM",
        modelTypeName: "Fire Alarm",
        modelTypeId: "FIREALARM",
        id: 11,
        name: "Ei3016 Optisch Alarm",
        reference: "Ei3016",
        description: "Ei/Aico Ei3016 Optical Alarm",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 132,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Ei3016 Events",
            scheduleReference: "Ei3016",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: -59,
        batteryVoltage: null,
        lastSeenDate: "2023-06-11T17:39:24.883Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "tony.boyle@aico.co.uk",
        iccid: "",
        age: 1495,
        lifePercentage: 63,
      },
      lifetimeMonths: 132,
      locationName: "Hallway 1",
      physicalSerialNumber: "E7E5D7F3",
      address: {
        uprn: "TB001_016474",
        flatIdentifier: null,
        nameNumber: "6 Orchard Bank",
        street: " ",
        locality: null,
        county: null,
        city: "Carluke",
        postcode: "ML85FA",
        country: "GB",
      },
    },
    {
      propertyId: "da6458c5-ec1e-4b53-9d0e-9d3f0969910a",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_RSM_Demo_OBNEW",
      propertyDisplayReference: "RSM_Demo_OBNEW",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "14 Trafalgar Rise Clanfield WATERLOOVILLE PO80PN GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1025 Temperature, Humidity & CO2 Sensor",
      modelTypeId: "ENVCO2SENSOR",
      modelReference: "Ei1025",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: null,
      batteryVoltage: null,
      lastSeenDate: "2023-06-15T17:12:35.885Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Oliver Barlow",
      iccid: "",
      id: "011e80a4-d612-457a-b860-406ce93a6925",
      name: "Ei1025 Bedroom 1",
      serialNumber: "C3CCD0E8-00058C50",
      deviceSeqId: 249008,
      virtualId: "028ff24d-63a0-4b39-a611-69f9f87d4b3e",
      locationId: "BEDROOM1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ENV",
      parentId: null,
      installationDate: "2023-06-15T17:01:40.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2032-11-15T00:00:00.000Z",
      createdAt: "2023-06-15T17:05:17.530Z",
      updatedAt: "2023-06-15T17:05:17.530Z",
      hidden: false,
      modelId: 71,
      deviceId: "011e80a4-d612-457a-b860-406ce93a6925",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Bedroom 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "028ff24d-63a0-4b39-a611-69f9f87d4b3e",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "00058C50",
        },
        {
          key: "VIRTUALID",
          value: "028ff24d-63a0-4b39-a611-69f9f87d4b3e",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "RSM_Demo_OBNEW_039543",
        },
        {
          key: "aicovpid",
          value: "039543",
        },
        {
          key: "POSTCODE",
          value: "PO80PN",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "ENVCO2SENSOR",
        modelTypeName: "Environment & Carbon Dioxide Sensor",
        modelTypeId: "ENVCO2SENSOR",
        id: 71,
        name: "Ei1025 Temperatuur-, Vochtigheid- & CO2-sensor",
        reference: "Ei1025",
        description: "Ei/Aico Ei1025 Temperature, Humidity & CO2 Sensor",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2021-05-04T12:03:42.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 120,
        active: true,
        isExperimental: false,
        readingTypes: [
          {
            measurementUnitId: "g/m3",
            readingTypeId: "environment.absolutehumidity.indoor",
          },
          {
            measurementUnitId: "ppm",
            readingTypeId: "environment.co2.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.feelsliketemperature.indoor",
          },
          {
            measurementUnitId: "RH",
            readingTypeId: "environment.humidity.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.temperature.indoor",
          },
        ],
        schedules: [],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: null,
        batteryVoltage: null,
        lastSeenDate: "2023-06-15T17:12:35.885Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Oliver Barlow",
        iccid: "",
        age: 955,
        lifePercentage: 77,
      },
      lifetimeMonths: 120,
      locationName: "Bedroom 1",
      physicalSerialNumber: "00058C50",
      address: {
        uprn: "RSM_Demo_OBNEW_039543",
        flatIdentifier: null,
        nameNumber: "14 Trafalgar Rise",
        street: "Clanfield",
        locality: null,
        county: null,
        city: "WATERLOOVILLE",
        postcode: "PO80PN",
        country: "GB",
      },
    },
    {
      propertyId: "f6b07f59-31c3-4f2c-8dde-644f01cae8c4",
      properyStatusId: "ACTIVE",
      propertyReference: "AICODEMO_TestGateway",
      propertyDisplayReference: "TestGateway",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "Test address  Bristol BT11AA GB",
      landlordId: "264ba2cf-ec3f-11eb-aa14-0a627a563cd4",
      landlordReference: "AICODEMO",
      landlordName: "Aico Demo",
      modelName: "Ei1120 OK Button",
      modelTypeId: "TEC_IMOK",
      modelReference: "Ei1120",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: null,
      batteryVoltage: null,
      lastSeenDate: null,
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Robbie  Morrissey",
      iccid: "",
      id: "017d7083-6ddf-4cb9-a318-7b547e41d878",
      name: "Ei1130 Attic",
      serialNumber: "C3C2CEDA-06814420",
      deviceSeqId: 262458,
      virtualId: "ad2f52a5-865c-4982-a4f9-a419ce7a9f68",
      locationId: "ATTIC",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2024-01-25T10:40:24.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2034-01-23T00:00:00.000Z",
      createdAt: "2024-01-25T12:13:24.242Z",
      updatedAt: "2024-01-25T12:13:24.242Z",
      hidden: false,
      modelId: 84,
      deviceId: "017d7083-6ddf-4cb9-a318-7b547e41d878",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Attic",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "ad2f52a5-865c-4982-a4f9-a419ce7a9f68",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "06814420",
        },
        {
          key: "VIRTUALID",
          value: "ad2f52a5-865c-4982-a4f9-a419ce7a9f68",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "TestGateway_002745",
        },
        {
          key: "aicovpid",
          value: "002745",
        },
        {
          key: "POSTCODE",
          value: "BT11AA",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "TEC_IMOK",
        modelTypeName: "T.E.C. I'm OK Button ",
        modelTypeId: "TEC_IMOK",
        id: 84,
        name: "Ei1130 OK Knop",
        reference: "Ei1120",
        description: "Ei/Aico Ei1120 OK Button",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2024-01-25T12:12:33.000Z",
        updatedAt: "2024-06-25T10:47:43.066Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 120,
        active: true,
        isExperimental: true,
        readingTypes: [],
        schedules: [],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: null,
        batteryVoltage: null,
        lastSeenDate: null,
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Robbie  Morrissey",
        iccid: "",
        age: 521,
        lifePercentage: 88,
      },
      lifetimeMonths: 120,
      locationName: "Attic",
      physicalSerialNumber: "06814420",
      address: {
        uprn: "TestGateway_002745",
        flatIdentifier: null,
        nameNumber: "Test address",
        street: "",
        locality: null,
        county: null,
        city: "Bristol",
        postcode: "BT11AA",
        country: "GB",
      },
    },
    {
      propertyId: "01ad3cd5-f9d3-414b-9183-52ca1597b6db",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_-_APH_My_house",
      propertyDisplayReference: "My house",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "2a Denbigh Road  London W138PX GB",
      landlordId: "b7009970-4f2f-424c-be4d-ca9ad0f34c12",
      landlordReference: "AICO_HOMELINK_DEMO_-_APH",
      landlordName: "Aico HomeLINK Demo - APH",
      modelName: "Gas & Electricity Smart Meter",
      modelTypeId: "SMARTMETERGASELEC",
      modelReference: "SMARTGE",
      manufacturerReference: "SmartDCC",
      modelSyncMethodId: "PUSH",
      signalStrength: null,
      batteryVoltage: null,
      lastSeenDate: null,
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "homelink-resident-app",
      iccid: null,
      id: "01ad3cd5-f9d3-414b-9183-52ca1597b6de",
      name: "Gas & Electric Smart Meter",
      serialNumber: "2000057539160",
      deviceSeqId: 201785,
      virtualId: null,
      locationId: "ELEC",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ENERGYMON",
      parentId: null,
      installationDate: "2022-01-01T00:00:00.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: null,
      createdAt: "2023-02-10T10:18:16.000Z",
      updatedAt: "2024-06-16T12:01:53.615Z",
      hidden: false,
      modelId: 73,
      deviceId: "01ad3cd5-f9d3-414b-9183-52ca1597b6de",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PULL",
      roomName: "Electrical Cupboard",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "2000057539160",
      deviceIdentifiers: [
        {
          key: "SerialNumber",
          value: "2000057539160",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "My house_017261",
        },
        {
          key: "aicovpid",
          value: "017261",
        },
        {
          key: "POSTCODE",
          value: "W138PX",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "SmartDCC",
        manufacturerName: "Smart DCC",
        modelTypeReference: "SMARTMETERGASELEC",
        modelTypeName: "Smart Meter Gas & Electricity",
        modelTypeId: "SMARTMETERGASELEC",
        id: 73,
        name: "Gas & Elektriciteit Slimme Meter",
        reference: "SMARTGE",
        description: "Smart Meter: Gas & Electricity, Consumption & Tariff",
        manufacturerId: "daf3ff5e-c7e7-441a-bd2b-f1dab510ce9f",
        createdAt: "2022-10-14T15:14:11.000Z",
        updatedAt: "2022-10-14T15:14:11.615Z",
        integrationNamespace: null,
        connectivityTypeId: "VIRTUAL",
        syncMethodId: "PUSH",
        lifetimeMonths: 9999,
        active: true,
        isExperimental: true,
        readingTypes: [
          {
            measurementUnitId: "KW/h",
            readingTypeId: "electricity.power.hour",
          },
          {
            measurementUnitId: "KW/h",
            readingTypeId: "gas.power.hour",
          },
          {
            measurementUnitId: "GBP",
            readingTypeId: "tariff.electricity.power.hour",
          },
          {
            measurementUnitId: "GBP",
            readingTypeId: "tariff.electricity.standingCharge.day",
          },
          {
            measurementUnitId: "GBP",
            readingTypeId: "tariff.gas.power.hour",
          },
          {
            measurementUnitId: "GBP",
            readingTypeId: "tariff.gas.standingCharge.day",
          },
        ],
        schedules: [
          {
            cronExpression: "*/30 * * * *",
            granularityUnitId: "minutes",
            destinationId: "SENSORIUM",
            granularityValue: 30,
            scheduleName: "Smart Meter Gas & Electricity",
            scheduleReference: "73",
            batchSize: 100,
            freshness: -3600,
            readingGroupTypeName: "Data",
            readingTypes: [
              {
                measurementUnitId: "KW/h",
                readingTypeId: "electricity.power.hour",
              },
              {
                measurementUnitId: "KW/h",
                readingTypeId: "gas.power.hour",
              },
              {
                measurementUnitId: "m3",
                readingTypeId: "gas.volume",
              },
              {
                measurementUnitId: "GBP",
                readingTypeId: "tariff.electricity.power.hour",
              },
              {
                measurementUnitId: "GBP",
                readingTypeId: "tariff.electricity.standingCharge.day",
              },
              {
                measurementUnitId: "GBP",
                readingTypeId: "tariff.gas.power.hour",
              },
              {
                measurementUnitId: "GBP",
                readingTypeId: "tariff.gas.standingCharge.day",
              },
            ],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: null,
        batteryVoltage: null,
        lastSeenDate: null,
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "homelink-resident-app",
        iccid: null,
      },
      lifetimeMonths: 9999,
      locationName: "Electrical Cupboard",
      physicalSerialNumber: "2000057539160",
      address: {
        uprn: "My house_017261",
        flatIdentifier: null,
        nameNumber: "2a Denbigh Road",
        street: "",
        locality: null,
        county: null,
        city: "London",
        postcode: "W138PX",
        country: "GB",
      },
    },
    {
      propertyId: "fad42f4d-14f8-4eb7-aceb-acc184d6791e",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO-DEMO-2_CONTROL_007",
      propertyDisplayReference: "CONTROL_007",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress:
        "16a Cuthbert Avenue Redwood Bristol Stirlingshire BS26GT GB",
      landlordId: "eabfa8b2-f703-4dfc-8a29-722dd9e646c3",
      landlordReference: "AICO-DEMO-2",
      landlordName: "Aico Demo 2",
      modelName: "Ei1025 Temperature, Humidity & CO2 Sensor",
      modelTypeId: "ENVCO2SENSOR",
      modelReference: "Ei1025",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: 4,
      batteryVoltage: null,
      lastSeenDate: null,
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "andy.smith@aico.co.uk",
      iccid: null,
      id: "01f419d0-c760-43e7-ae11-a4f471a6f911",
      name: "Elsys ersco2",
      serialNumber: "80D79",
      deviceSeqId: 1538,
      virtualId: null,
      locationId: "BEDROOM1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ENV",
      parentId: null,
      installationDate: "2021-06-14T11:21:52.207Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2031-08-14T11:21:52.207Z",
      createdAt: "2021-11-04T14:07:14.400Z",
      updatedAt: "2024-06-25T13:48:19.255Z",
      hidden: false,
      modelId: 71,
      deviceId: "01f419d0-c760-43e7-ae11-a4f471a6f911",
      eventStatusId: "CHECK_INSTALL",
      eventStatusDescription: "Check Installation",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Bedroom 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "80D79",
      deviceIdentifiers: [
        {
          key: "originalId",
          value: "OLD_63d97fb4-111a-4eda-b106-53964993ed15",
        },
        {
          key: "originalSerial",
          value: "OLD_EF3C8D",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "POSTCODE",
          value: "BS26GT",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "ENVCO2SENSOR",
        modelTypeName: "Environment & Carbon Dioxide Sensor",
        modelTypeId: "ENVCO2SENSOR",
        id: 71,
        name: "Ei1025 Temperatuur-, Vochtigheid- & CO2-sensor",
        reference: "Ei1025",
        description: "Ei/Aico Ei1025 Temperature, Humidity & CO2 Sensor",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2021-05-04T12:03:42.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 120,
        active: true,
        isExperimental: false,
        readingTypes: [
          {
            measurementUnitId: "g/m3",
            readingTypeId: "environment.absolutehumidity.indoor",
          },
          {
            measurementUnitId: "ppm",
            readingTypeId: "environment.co2.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.feelsliketemperature.indoor",
          },
          {
            measurementUnitId: "RH",
            readingTypeId: "environment.humidity.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.temperature.indoor",
          },
        ],
        schedules: [],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: 4,
        batteryVoltage: null,
        lastSeenDate: null,
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "andy.smith@aico.co.uk",
        iccid: null,
        age: 1414,
        lifePercentage: 65,
      },
      lifetimeMonths: 120,
      locationName: "Bedroom 1",
      physicalSerialNumber: "80D79",
      address: {
        uprn: null,
        flatIdentifier: "",
        nameNumber: "16a",
        street: "Cuthbert Avenue",
        locality: "Redwood",
        county: "Stirlingshire",
        city: "Bristol",
        postcode: "BS26GT",
        country: "GB",
      },
    },
    {
      propertyId: "da6458c5-ec1e-4b53-9d0e-9d3f0969910a",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_RSM_Demo_OBNEW",
      propertyDisplayReference: "RSM_Demo_OBNEW",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "14 Trafalgar Rise Clanfield WATERLOOVILLE PO80PN GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1000G Smartlink Gateway",
      modelTypeId: "GATEWAY",
      modelReference: "Ei1000G",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -63,
      batteryVoltage: null,
      lastSeenDate: "2023-06-18T07:41:58.532Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Oliver Barlow",
      iccid: "8935302170702236451",
      id: "021b0a19-26f3-4e41-a1e2-836a07600e80",
      name: "Ei1000G Hallway 1",
      serialNumber: "C3CCD0E8",
      deviceSeqId: 249010,
      virtualId: "263f8711-5aa7-43ce-bfc7-159582c312d7",
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "IDGW",
      parentId: null,
      installationDate: "2023-06-15T17:01:40.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2034-02-27T00:00:00.000Z",
      createdAt: "2023-06-15T17:05:17.534Z",
      updatedAt: "2024-06-25T13:20:01.433Z",
      hidden: false,
      modelId: 4,
      deviceId: "021b0a19-26f3-4e41-a1e2-836a07600e80",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "263f8711-5aa7-43ce-bfc7-159582c312d7",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "C3CCD0E8",
        },
        {
          key: "VIRTUALID",
          value: "263f8711-5aa7-43ce-bfc7-159582c312d7",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "RSM_Demo_OBNEW_039543",
        },
        {
          key: "aicovpid",
          value: "039543",
        },
        {
          key: "POSTCODE",
          value: "PO80PN",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "GATEWAY",
        modelTypeName: "Gateway",
        modelTypeId: "GATEWAY",
        id: 4,
        name: "Ei1000G Smartlink Gateway",
        reference: "Ei1000G",
        description: "Gateway for alarms",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "GSM",
        syncMethodId: "PUSH",
        lifetimeMonths: 66,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Gateway Events",
            scheduleReference: "Ei1000G",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: -63,
        batteryVoltage: null,
        lastSeenDate: "2023-06-18T07:41:58.532Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Oliver Barlow",
        iccid: "8935302170702236451",
        age: 486,
        lifePercentage: 88,
      },
      lifetimeMonths: 66,
      locationName: "Hallway 1",
      physicalSerialNumber: "C3CCD0E8",
      address: {
        uprn: "RSM_Demo_OBNEW_039543",
        flatIdentifier: null,
        nameNumber: "14 Trafalgar Rise",
        street: "Clanfield",
        locality: null,
        county: null,
        city: "WATERLOOVILLE",
        postcode: "PO80PN",
        country: "GB",
      },
    },
    {
      propertyId: "8efdd74d-b5e0-47fb-9019-9b6fbc39675f",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO-DEMO-1_CONTROL_003",
      propertyDisplayReference: "CONTROL_003",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "21 Bishopworth Bristol BS231MU GB",
      landlordId: "c3c54bf6-4acd-4788-94e7-7b5085413f73",
      landlordReference: "AICO-DEMO-1",
      landlordName: "Aico Demo 1",
      modelName: "Ei208 CO Alarm",
      modelTypeId: "COALARM",
      modelReference: "Ei208",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: 4,
      batteryVoltage: null,
      lastSeenDate: null,
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "andy.smith@aico.co.uk",
      iccid: null,
      id: "0231f2f3-82a5-44fb-b1f5-d743083d5f5e",
      name: "",
      serialNumber: "6C6920",
      deviceSeqId: 1725,
      virtualId: null,
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2020-11-02T17:23:16.829Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2030-07-02T17:23:16.829Z",
      createdAt: "2021-11-04T13:19:14.724Z",
      updatedAt: "2023-03-21T14:37:00.499Z",
      hidden: false,
      modelId: 8,
      deviceId: "0231f2f3-82a5-44fb-b1f5-d743083d5f5e",
      eventStatusId: "ALARM",
      eventStatusDescription: "Alarm",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "6C6920",
      deviceIdentifiers: [
        {
          key: "originalId",
          value: "OLD_0ddb1b61-9f99-4a58-a85e-5e12f7dbcc95",
        },
        {
          key: "originalSerial",
          value: "OLD_441ED",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "POSTCODE",
          value: "BS231MU",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "COALARM",
        modelTypeName: "Carbon Monoxide Alarm",
        modelTypeId: "COALARM",
        id: 8,
        name: "Ei208 CO Alarm",
        reference: "Ei208",
        description: "Ei/Aico Ei208 CO Alarm",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 132,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Ei208 Events",
            scheduleReference: "Ei208",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [
        {
          statusId: "ACTIVE",
          id: "ed534d25-029b-4337-8969-78a9323e5e72",
          title: "High level CO detected",
          description: "High level CO detected for Ei208 CO Alarm",
          raisedDate: "2022-06-11T19:38:07.768Z",
          eventId: "ed534d25-029b-4337-8969-78a9323e5e72",
          deviceId: "0231f2f3-82a5-44fb-b1f5-d743083d5f5e",
          propertyId: "8efdd74d-b5e0-47fb-9019-9b6fbc39675f",
          eventTypeId: "CO_HIGH_LEVEL_ALARM",
        },
      ],
      metadata: {
        signalStrength: 4,
        batteryVoltage: null,
        lastSeenDate: null,
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "andy.smith@aico.co.uk",
        iccid: null,
        age: 1822,
        lifePercentage: 55,
      },
      lifetimeMonths: 132,
      locationName: "Hallway 1",
      physicalSerialNumber: "6C6920",
      address: {
        uprn: null,
        flatIdentifier: null,
        nameNumber: "21",
        street: null,
        locality: "Bishopworth",
        county: null,
        city: "Bristol",
        postcode: "BS231MU",
        country: "GB",
      },
    },
    {
      propertyId: "720dfa3e-d1ff-44ec-aa52-6a61f4c7bf8b",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_Brads_House_033059",
      propertyDisplayReference: "Brads House",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "3 Bluegown Avenue  Leybourne, WEST MALLING ME195FN GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1025 Temperature, Humidity & CO2 Sensor",
      modelTypeId: "ENVCO2SENSOR",
      modelReference: "Ei1025",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -65,
      batteryVoltage: null,
      lastSeenDate: "2023-06-17T23:43:27.688Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Bradley Wain",
      iccid: "",
      id: "0247f7f1-bb7a-468b-965a-35aab2b6dae1",
      name: "Ei1025 Bedroom 1",
      serialNumber: "000F056A",
      deviceSeqId: 201712,
      virtualId: "96410a76-093c-4078-b6a6-56e69ac503d5",
      locationId: "BEDROOM1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ENV",
      parentId: null,
      installationDate: "2023-02-09T00:00:00.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2033-03-14T00:00:00.000Z",
      createdAt: "2023-02-09T16:39:01.384Z",
      updatedAt: "2023-02-09T17:03:17.777Z",
      hidden: false,
      modelId: 71,
      deviceId: "0247f7f1-bb7a-468b-965a-35aab2b6dae1",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Bedroom 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "96410a76-093c-4078-b6a6-56e69ac503d5",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "000F056A",
        },
        {
          key: "VIRTUALID",
          value: "96410a76-093c-4078-b6a6-56e69ac503d5",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "Brads House_033059",
        },
        {
          key: "aicovpid",
          value: "033059",
        },
        {
          key: "POSTCODE",
          value: "ME195FN",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "ENVCO2SENSOR",
        modelTypeName: "Environment & Carbon Dioxide Sensor",
        modelTypeId: "ENVCO2SENSOR",
        id: 71,
        name: "Ei1025 Temperatuur-, Vochtigheid- & CO2-sensor",
        reference: "Ei1025",
        description: "Ei/Aico Ei1025 Temperature, Humidity & CO2 Sensor",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2021-05-04T12:03:42.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 120,
        active: true,
        isExperimental: false,
        readingTypes: [
          {
            measurementUnitId: "g/m3",
            readingTypeId: "environment.absolutehumidity.indoor",
          },
          {
            measurementUnitId: "ppm",
            readingTypeId: "environment.co2.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.feelsliketemperature.indoor",
          },
          {
            measurementUnitId: "RH",
            readingTypeId: "environment.humidity.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.temperature.indoor",
          },
        ],
        schedules: [],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: -65,
        batteryVoltage: null,
        lastSeenDate: "2023-06-17T23:43:27.688Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Bradley Wain",
        iccid: "",
        age: 836,
        lifePercentage: 80,
      },
      lifetimeMonths: 120,
      locationName: "Bedroom 1",
      physicalSerialNumber: "000F056A",
      address: {
        uprn: "Brads House_033059",
        flatIdentifier: null,
        nameNumber: "3 Bluegown Avenue",
        street: "",
        locality: null,
        county: null,
        city: "Leybourne, WEST MALLING",
        postcode: "ME195FN",
        country: "GB",
      },
    },
    {
      propertyId: "0f1624f9-c6ef-418b-8498-7967cdcfeb42",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_RSM_Static_OB",
      propertyDisplayReference: "RSM_Static_OB",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress:
        "14 Trafalgar Rise Clanfield Waterlooville Hampshire PO80PN GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1020 Temperature & Humidity Sensor",
      modelTypeId: "ENVSENSOR",
      modelReference: "Ei1020",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -54,
      batteryVoltage: null,
      lastSeenDate: "2023-07-18T13:23:36.797Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "oliver.barlow@aico.co.uk",
      iccid: "",
      id: "027dd8a6-35fb-47aa-b953-4d81641458ba",
      name: "Ei1020 Kitchen",
      serialNumber: "0002B7AA",
      deviceSeqId: 1954,
      virtualId: "A282B27C-4909-404F-B8CB-D32E090741D0",
      locationId: "KITCHEN",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ENV",
      parentId: null,
      installationDate: "2021-12-29T12:14:05.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2032-08-16T00:00:00.000Z",
      createdAt: "2021-12-29T12:44:08.420Z",
      updatedAt: "2022-10-05T10:55:17.679Z",
      hidden: false,
      modelId: 70,
      deviceId: "027dd8a6-35fb-47aa-b953-4d81641458ba",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Kitchen",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "A282B27C-4909-404F-B8CB-D32E090741D0",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "0002B7AA",
        },
        {
          key: "VIRTUALID",
          value: "A282B27C-4909-404F-B8CB-D32E090741D0",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "RSM_Static_OB_016413",
        },
        {
          key: "aicovpid",
          value: "016413",
        },
        {
          key: "POSTCODE",
          value: "PO80PN",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "ENVSENSOR",
        modelTypeName: "Environment Sensor",
        modelTypeId: "ENVSENSOR",
        id: 70,
        name: "Ei1020 Temperatuur- & Vochtigheidssensor",
        reference: "Ei1020",
        description: "Ei/Aico Ei1020 Temperature & Humidity Sensor",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2021-05-04T12:03:42.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 120,
        active: true,
        isExperimental: false,
        readingTypes: [
          {
            measurementUnitId: "g/m3",
            readingTypeId: "environment.absolutehumidity.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.feelsliketemperature.indoor",
          },
          {
            measurementUnitId: "RH",
            readingTypeId: "environment.humidity.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.temperature.indoor",
          },
        ],
        schedules: [],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: -54,
        batteryVoltage: null,
        lastSeenDate: "2023-07-18T13:23:36.797Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "oliver.barlow@aico.co.uk",
        iccid: "",
        age: 1046,
        lifePercentage: 74,
      },
      lifetimeMonths: 120,
      locationName: "Kitchen",
      physicalSerialNumber: "0002B7AA",
      address: {
        uprn: "RSM_Static_OB_016413",
        flatIdentifier: null,
        nameNumber: "14",
        street: "Trafalgar Rise",
        locality: "Clanfield",
        county: "Hampshire",
        city: "Waterlooville",
        postcode: "PO80PN",
        country: "GB",
      },
    },
    {
      propertyId: "add1a247-8274-412b-a6a9-aee5d357ab77",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_TB001",
      propertyDisplayReference: "TB001",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "6 Orchard Bank   Carluke ML85FA GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei208 CO Alarm",
      modelTypeId: "COALARM",
      modelReference: "Ei208",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -65,
      batteryVoltage: null,
      lastSeenDate: "2023-07-07T01:12:05.378Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "tony.boyle@aico.co.uk",
      iccid: "",
      id: "02a7adee-6cb0-470d-b414-eb4590832c77",
      name: "Ei208 Living room",
      serialNumber: "F4EBECFF",
      deviceSeqId: 2075,
      virtualId: "EF9A83FB-480F-4844-BFD6-0EA09C287980",
      locationId: "LIVINGROOM",
      subLocationId: null,
      locationNickname: "Log Burner",
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2022-01-05T17:47:21.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2030-04-08T00:00:00.000Z",
      createdAt: "2022-01-05T18:02:37.995Z",
      updatedAt: "2022-10-05T10:55:19.696Z",
      hidden: false,
      modelId: 8,
      deviceId: "02a7adee-6cb0-470d-b414-eb4590832c77",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Living Room",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "EF9A83FB-480F-4844-BFD6-0EA09C287980",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "F4EBECFF",
        },
        {
          key: "VIRTUALID",
          value: "EF9A83FB-480F-4844-BFD6-0EA09C287980",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "TB001_016474",
        },
        {
          key: "aicovpid",
          value: "016474",
        },
        {
          key: "POSTCODE",
          value: "ML85FA",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "COALARM",
        modelTypeName: "Carbon Monoxide Alarm",
        modelTypeId: "COALARM",
        id: 8,
        name: "Ei208 CO Alarm",
        reference: "Ei208",
        description: "Ei/Aico Ei208 CO Alarm",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 132,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Ei208 Events",
            scheduleReference: "Ei208",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: -65,
        batteryVoltage: null,
        lastSeenDate: "2023-07-07T01:12:05.378Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "tony.boyle@aico.co.uk",
        iccid: "",
        age: 1907,
        lifePercentage: 53,
      },
      lifetimeMonths: 132,
      locationName: "Living Room",
      physicalSerialNumber: "F4EBECFF",
      address: {
        uprn: "TB001_016474",
        flatIdentifier: null,
        nameNumber: "6 Orchard Bank",
        street: " ",
        locality: null,
        county: null,
        city: "Carluke",
        postcode: "ML85FA",
        country: "GB",
      },
    },
    {
      propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_Mitch_flat",
      propertyDisplayReference: "Mitch_flat",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "611 Airpoint Skypark Road  Bristol  BS33NQ GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1000G Smartlink Gateway",
      modelTypeId: "GATEWAY",
      modelReference: "Ei1000G",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -120,
      batteryVoltage: null,
      lastSeenDate: "2023-10-11T11:15:48.000Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Mitch Ford",
      iccid: "8935302170822319179",
      id: "0465b849-ed71-45b7-a980-94d5abf921d7",
      name: "Ei1000G Study",
      serialNumber: "C3C1EAC1",
      deviceSeqId: 3430,
      virtualId: "2D891FCE-4841-4B0E-8FDD-F80F389B29BB",
      locationId: "STUDY",
      subLocationId: null,
      locationNickname: "Office",
      statusId: "ACTIVE",
      typeId: "IDGW",
      parentId: null,
      installationDate: "2022-01-26T00:00:00.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2031-02-24T00:00:00.000Z",
      createdAt: "2022-01-26T11:39:11.211Z",
      updatedAt: "2023-10-06T12:18:52.254Z",
      hidden: false,
      modelId: 4,
      deviceId: "0465b849-ed71-45b7-a980-94d5abf921d7",
      eventStatusId: "WARNING",
      eventStatusDescription: "Poor",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Study",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "2D891FCE-4841-4B0E-8FDD-F80F389B29BB",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "C3C1EAC1",
        },
        {
          key: "VIRTUALID",
          value: "2D891FCE-4841-4B0E-8FDD-F80F389B29BB",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "Mitch_flat_017387",
        },
        {
          key: "aicovpid",
          value: "017387",
        },
        {
          key: "POSTCODE",
          value: "BS33NQ",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "GATEWAY",
        modelTypeName: "Gateway",
        modelTypeId: "GATEWAY",
        id: 4,
        name: "Ei1000G Smartlink Gateway",
        reference: "Ei1000G",
        description: "Gateway for alarms",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "GSM",
        syncMethodId: "PUSH",
        lifetimeMonths: 66,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Gateway Events",
            scheduleReference: "Ei1000G",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [
        {
          statusId: "ACTIVE",
          id: "dfaf87ac-381f-44c3-8817-e441c9b92080",
          title: "Gateway Offline",
          description: "C3C1EAC1 in location Study: Gateway Offline",
          raisedDate: "2023-08-16T02:01:24.000Z",
          eventId: "dfaf87ac-381f-44c3-8817-e441c9b92080",
          deviceId: "0465b849-ed71-45b7-a980-94d5abf921d7",
          propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
          eventTypeId: "GATEWAY_OFFLINE",
        },
        {
          statusId: "ACTIVE",
          id: "ef5da756-2295-4056-b0a2-56dbb0e989b5",
          title: "Gateway Offline",
          description: "C3C1EAC1 in location Study: Gateway Offline",
          raisedDate: "2024-02-07T22:44:31.000Z",
          eventId: "ef5da756-2295-4056-b0a2-56dbb0e989b5",
          deviceId: "0465b849-ed71-45b7-a980-94d5abf921d7",
          propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
          eventTypeId: "GATEWAY_OFFLINE",
        },
        {
          statusId: "ACTIVE",
          id: "fd50849b-2ffa-4a5e-bbd5-02625f777151",
          title: "Gateway Offline",
          description: "C3C1EAC1 in location Study: Gateway Offline",
          raisedDate: "2024-03-05T07:52:57.000Z",
          eventId: "fd50849b-2ffa-4a5e-bbd5-02625f777151",
          deviceId: "0465b849-ed71-45b7-a980-94d5abf921d7",
          propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
          eventTypeId: "GATEWAY_OFFLINE",
        },
        {
          statusId: "ACTIVE",
          id: "eef3e7d7-fe5f-4e92-bfb1-a01526a16247",
          title: "Gateway Offline",
          description: "C3C1EAC1 in location Study: Gateway Offline",
          raisedDate: "2024-03-22T02:52:41.000Z",
          eventId: "eef3e7d7-fe5f-4e92-bfb1-a01526a16247",
          deviceId: "0465b849-ed71-45b7-a980-94d5abf921d7",
          propertyId: "c411a2bd-c856-433f-babe-6294b6c29e35",
          eventTypeId: "GATEWAY_OFFLINE",
        },
      ],
      metadata: {
        signalStrength: -120,
        batteryVoltage: null,
        lastSeenDate: "2023-10-11T11:15:48.000Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Mitch Ford",
        iccid: "8935302170822319179",
        age: 1585,
        lifePercentage: 61,
      },
      lifetimeMonths: 66,
      locationName: "Study",
      physicalSerialNumber: "C3C1EAC1",
      address: {
        uprn: "Mitch_flat_017387",
        flatIdentifier: null,
        nameNumber: "611 Airpoint",
        street: "Skypark Road",
        locality: "",
        county: "",
        city: "Bristol",
        postcode: "BS33NQ",
        country: "GB",
      },
    },
    {
      propertyId: "1ed0a87c-2132-47db-ba67-af229c7f6251",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO-DEMO-1_CONTROL_007",
      propertyDisplayReference: "CONTROL_007",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress:
        "16a Cuthbert Avenue Redwood Bristol Stirlingshire BS26GT GB",
      landlordId: "c3c54bf6-4acd-4788-94e7-7b5085413f73",
      landlordReference: "AICO-DEMO-1",
      landlordName: "Aico Demo 1",
      modelName: "Ei1000G Smartlink Gateway",
      modelTypeId: "GATEWAY",
      modelReference: "Ei1000G",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: 4,
      batteryVoltage: null,
      lastSeenDate: "2022-01-28T03:24:07.000Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "andy.smith@aico.co.uk",
      iccid: null,
      id: "0487e659-9b36-4835-a608-1e56d6778440",
      name: "",
      serialNumber: "F61F1F",
      deviceSeqId: 3532,
      virtualId: null,
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2020-11-05T15:13:57.466Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2030-10-05T15:13:57.466Z",
      createdAt: "2021-11-04T13:35:29.453Z",
      updatedAt: "2024-06-25T13:20:01.433Z",
      hidden: false,
      modelId: 4,
      deviceId: "0487e659-9b36-4835-a608-1e56d6778440",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "F61F1F",
      deviceIdentifiers: [
        {
          key: "originalId",
          value: "OLD_287c4ac5-c1af-497f-935c-c9de5c22ebcd",
        },
        {
          key: "originalSerial",
          value: "OLD_2041D1",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "POSTCODE",
          value: "BS26GT",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "GATEWAY",
        modelTypeName: "Gateway",
        modelTypeId: "GATEWAY",
        id: 4,
        name: "Ei1000G Smartlink Gateway",
        reference: "Ei1000G",
        description: "Gateway for alarms",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "GSM",
        syncMethodId: "PUSH",
        lifetimeMonths: 66,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Gateway Events",
            scheduleReference: "Ei1000G",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: 4,
        batteryVoltage: null,
        lastSeenDate: "2022-01-28T03:24:07.000Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "andy.smith@aico.co.uk",
        iccid: null,
        age: 1727,
        lifePercentage: 58,
      },
      lifetimeMonths: 66,
      locationName: "Hallway 1",
      physicalSerialNumber: "F61F1F",
      address: {
        uprn: null,
        flatIdentifier: "",
        nameNumber: "16a",
        street: "Cuthbert Avenue",
        locality: "Redwood",
        county: "Stirlingshire",
        city: "Bristol",
        postcode: "BS26GT",
        country: "GB",
      },
    },
    {
      propertyId: "ccdf8e60-d90a-4d5e-96fc-2a05a8ac574b",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_Aico_Demo_Session",
      propertyDisplayReference: "Aico Demo Session",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "4 Cotham Grove  Bristol  BS66AL GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei650i Optical Alarm",
      modelTypeId: "FIREALARM",
      modelReference: "Ei650i",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: null,
      batteryVoltage: null,
      lastSeenDate: "2022-06-14T16:04:07.000Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Ryan Conway",
      iccid: "",
      id: "048d1840-7af6-4ded-b532-f62f3da794ed",
      name: "Ei650i Living room",
      serialNumber: "CDD9FEC3",
      deviceSeqId: 3551,
      virtualId: "0DD09804-51FD-4C9F-8F22-D2F24F831396",
      locationId: "LIVINGROOM",
      subLocationId: null,
      locationNickname: "Living Room",
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2022-06-14T16:42:57.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2033-04-25T00:00:00.000Z",
      createdAt: "2022-06-14T15:52:56.388Z",
      updatedAt: "2022-10-05T10:57:45.712Z",
      hidden: false,
      modelId: 58,
      deviceId: "048d1840-7af6-4ded-b532-f62f3da794ed",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Living Room",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "0DD09804-51FD-4C9F-8F22-D2F24F831396",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "CDD9FEC3",
        },
        {
          key: "VIRTUALID",
          value: "0DD09804-51FD-4C9F-8F22-D2F24F831396",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "Aico Demo Session_022927",
        },
        {
          key: "aicovpid",
          value: "022927",
        },
        {
          key: "POSTCODE",
          value: "SY108NR",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "FIREALARM",
        modelTypeName: "Fire Alarm",
        modelTypeId: "FIREALARM",
        id: 58,
        name: "Ei650i Optisch Alarm",
        reference: "Ei650i",
        description: "Ei/Aico Ei650i Optical Alarm",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2020-10-16T18:57:50.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 132,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "0 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Ei650i Events",
            scheduleReference: "Ei650i",
            batchSize: 100,
            freshness: -30,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: null,
        batteryVoltage: null,
        lastSeenDate: "2022-06-14T16:04:07.000Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Ryan Conway",
        iccid: "",
        age: 794,
        lifePercentage: 81,
      },
      lifetimeMonths: 132,
      locationName: "Living Room",
      physicalSerialNumber: "CDD9FEC3",
      address: {
        uprn: "Aico Demo Session_022927",
        flatIdentifier: null,
        nameNumber: "4",
        street: "Cotham Grove",
        locality: "",
        county: "",
        city: "Bristol",
        postcode: "BS66AL",
        country: "GB",
      },
    },
    {
      propertyId: "486b041e-16b4-476e-81dc-318c2f131090",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_ZZZA",
      propertyDisplayReference: "ZZZA",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "Sam Boot Stock  Chorley  PR75UW GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1000G Smartlink Gateway",
      modelTypeId: "GATEWAY",
      modelReference: "Ei1000G",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -81,
      batteryVoltage: null,
      lastSeenDate: "2023-06-22T08:26:01.769Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Sam Barker",
      iccid: "8935302170702234258",
      id: "04a119f6-4aff-4a70-85fc-cad545591de4",
      name: "Ei1000G Hallway 1",
      serialNumber: "C3CCCEF2",
      deviceSeqId: 249815,
      virtualId: "6e059203-f29b-49da-9c6c-bf84dcc146bc",
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: "Boot Stock",
      statusId: "ACTIVE",
      typeId: "IDGW",
      parentId: null,
      installationDate: "2023-06-19T07:09:01.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2034-02-27T00:00:00.000Z",
      createdAt: "2023-06-19T07:32:19.598Z",
      updatedAt: "2023-06-23T08:42:06.334Z",
      hidden: false,
      modelId: 4,
      deviceId: "04a119f6-4aff-4a70-85fc-cad545591de4",
      eventStatusId: "WARNING",
      eventStatusDescription: "Poor",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "6e059203-f29b-49da-9c6c-bf84dcc146bc",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "C3CCCEF2",
        },
        {
          key: "VIRTUALID",
          value: "6e059203-f29b-49da-9c6c-bf84dcc146bc",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "ZZZA_039631",
        },
        {
          key: "aicovpid",
          value: "039631",
        },
        {
          key: "POSTCODE",
          value: "PR75UW",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "GATEWAY",
        modelTypeName: "Gateway",
        modelTypeId: "GATEWAY",
        id: 4,
        name: "Ei1000G Smartlink Gateway",
        reference: "Ei1000G",
        description: "Gateway for alarms",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "GSM",
        syncMethodId: "PUSH",
        lifetimeMonths: 66,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Gateway Events",
            scheduleReference: "Ei1000G",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [
        {
          statusId: "ACTIVE",
          id: "dfc1f5b0-df97-480f-8be9-a946c44c8ac0",
          title: "Gateway Offline",
          description: "C3CCCEF2 in location Hallway 1: Gateway Offline",
          raisedDate: "2023-06-23T08:33:00.000Z",
          eventId: "dfc1f5b0-df97-480f-8be9-a946c44c8ac0",
          deviceId: "04a119f6-4aff-4a70-85fc-cad545591de4",
          propertyId: "486b041e-16b4-476e-81dc-318c2f131090",
          eventTypeId: "GATEWAY_OFFLINE",
        },
      ],
      metadata: {
        signalStrength: -81,
        batteryVoltage: null,
        lastSeenDate: "2023-06-22T08:26:01.769Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Sam Barker",
        iccid: "8935302170702234258",
        age: 486,
        lifePercentage: 88,
      },
      lifetimeMonths: 66,
      locationName: "Hallway 1",
      physicalSerialNumber: "C3CCCEF2",
      address: {
        uprn: "ZZZA_039631",
        flatIdentifier: null,
        nameNumber: "Sam Boot Stock",
        street: "",
        locality: null,
        county: null,
        city: "Chorley ",
        postcode: "PR75UW",
        country: "GB",
      },
    },
    {
      propertyId: "7d6c431e-5b74-436d-87bf-02b5a7f79c06",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_37_Den_Av",
      propertyDisplayReference: "37 Den Av",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "37 Denning Avenue  Croydon CR04DJ GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1000G Smartlink Gateway",
      modelTypeId: "GATEWAY",
      modelReference: "Ei1000G",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -79,
      batteryVoltage: null,
      lastSeenDate: "2023-07-18T13:23:52.468Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "rachel.wright@aico.co.uk",
      iccid: "8935302170820098742",
      id: "04b7dc57-31d7-4876-9913-9fcd80d17880",
      name: "Ei1000G Hallway 1",
      serialNumber: "C3C1CAF4",
      deviceSeqId: 3690,
      virtualId: "5D5C2331-D23A-480A-8EE7-4AE4E360CD3F",
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: "Under Big Cupboard",
      statusId: "ACTIVE",
      typeId: "IDGW",
      parentId: null,
      installationDate: "2021-12-01T00:00:00.000Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2030-12-23T00:00:00.000Z",
      createdAt: "2021-12-01T20:27:27.733Z",
      updatedAt: "2023-10-06T12:18:52.254Z",
      hidden: false,
      modelId: 4,
      deviceId: "04b7dc57-31d7-4876-9913-9fcd80d17880",
      eventStatusId: "WARNING",
      eventStatusDescription: "Poor",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "5D5C2331-D23A-480A-8EE7-4AE4E360CD3F",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "C3C1CAF4",
        },
        {
          key: "VIRTUALID",
          value: "5D5C2331-D23A-480A-8EE7-4AE4E360CD3F",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "37 Den Av_015393",
        },
        {
          key: "aicovpid",
          value: "015393",
        },
        {
          key: "POSTCODE",
          value: "CR04DJ",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "GATEWAY",
        modelTypeName: "Gateway",
        modelTypeId: "GATEWAY",
        id: 4,
        name: "Ei1000G Smartlink Gateway",
        reference: "Ei1000G",
        description: "Gateway for alarms",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "GSM",
        syncMethodId: "PUSH",
        lifetimeMonths: 66,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Gateway Events",
            scheduleReference: "Ei1000G",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [
        {
          statusId: "ACTIVE",
          id: "e2f4c097-933a-403b-b4f7-59f1705dc14f",
          title: "Gateway Offline",
          description: "C3C1CAF4 in location Hallway 1: Gateway Offline",
          raisedDate: "2023-09-13T04:02:25.000Z",
          eventId: "e2f4c097-933a-403b-b4f7-59f1705dc14f",
          deviceId: "04b7dc57-31d7-4876-9913-9fcd80d17880",
          propertyId: "7d6c431e-5b74-436d-87bf-02b5a7f79c06",
          eventTypeId: "GATEWAY_OFFLINE",
        },
        {
          statusId: "ACTIVE",
          id: "f7e1d28f-da9c-4d83-a48f-384d579e61ed",
          title: "Gateway Offline",
          description: "C3C1CAF4 in location Hallway 1: Gateway Offline",
          raisedDate: "2024-01-06T07:52:15.000Z",
          eventId: "f7e1d28f-da9c-4d83-a48f-384d579e61ed",
          deviceId: "04b7dc57-31d7-4876-9913-9fcd80d17880",
          propertyId: "7d6c431e-5b74-436d-87bf-02b5a7f79c06",
          eventTypeId: "GATEWAY_OFFLINE",
        },
        {
          statusId: "ACTIVE",
          id: "ebf97fa6-cd9e-44f7-9584-3d49169158ba",
          title: "Gateway Offline",
          description: "C3C1CAF4 in location Hallway 1: Gateway Offline",
          raisedDate: "2024-02-08T00:45:50.000Z",
          eventId: "ebf97fa6-cd9e-44f7-9584-3d49169158ba",
          deviceId: "04b7dc57-31d7-4876-9913-9fcd80d17880",
          propertyId: "7d6c431e-5b74-436d-87bf-02b5a7f79c06",
          eventTypeId: "GATEWAY_OFFLINE",
        },
        {
          statusId: "ACTIVE",
          id: "fbebc8cc-b06b-4c77-bfe9-6f012454dd41",
          title: "Gateway Offline",
          description: "C3C1CAF4 in location Hallway 1: Gateway Offline",
          raisedDate: "2024-04-04T13:41:37.000Z",
          eventId: "fbebc8cc-b06b-4c77-bfe9-6f012454dd41",
          deviceId: "04b7dc57-31d7-4876-9913-9fcd80d17880",
          propertyId: "7d6c431e-5b74-436d-87bf-02b5a7f79c06",
          eventTypeId: "GATEWAY_OFFLINE",
        },
      ],
      metadata: {
        signalStrength: -79,
        batteryVoltage: null,
        lastSeenDate: "2023-07-18T13:23:52.468Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "rachel.wright@aico.co.uk",
        iccid: "8935302170820098742",
        age: 1648,
        lifePercentage: 59,
      },
      lifetimeMonths: 66,
      locationName: "Hallway 1",
      physicalSerialNumber: "C3C1CAF4",
      address: {
        uprn: "37 Den Av_015393",
        flatIdentifier: null,
        nameNumber: "37 Denning Avenue",
        street: "",
        locality: null,
        county: null,
        city: "Croydon",
        postcode: "CR04DJ",
        country: "GB",
      },
    },
    {
      propertyId: "13faab41-1a1e-4888-9412-e7e9cf48a4a3",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_Silviu_SN",
      propertyDisplayReference: "Silviu_SN",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "5 Knoll Court, Knoll Hill  BRISTOL BS91QX GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1025 Temperature, Humidity & CO2 Sensor",
      modelTypeId: "ENVCO2SENSOR",
      modelReference: "Ei1025",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -60,
      batteryVoltage: null,
      lastSeenDate: "2023-07-18T14:03:25.701Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Silviu Nistor",
      iccid: "",
      id: "04bbcc6c-d77c-47ce-b3a3-7900b5d41ab2",
      name: "Ei1025 Bedroom 2",
      serialNumber: "002F578F",
      deviceSeqId: 206728,
      virtualId: "621de8ac-5c68-4b98-a76f-3e78a9e7447f",
      locationId: "BEDROOM2",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ENV",
      parentId: null,
      installationDate: "2023-02-22T14:12:08.879Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2033-12-05T00:00:00.000Z",
      createdAt: "2023-02-22T14:12:13.300Z",
      updatedAt: "2023-02-22T14:12:13.300Z",
      hidden: false,
      modelId: 71,
      deviceId: "04bbcc6c-d77c-47ce-b3a3-7900b5d41ab2",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Bedroom 2",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "621de8ac-5c68-4b98-a76f-3e78a9e7447f",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "002F578F",
        },
        {
          key: "VIRTUALID",
          value: "621de8ac-5c68-4b98-a76f-3e78a9e7447f",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "Silviu_SN_033760",
        },
        {
          key: "aicovpid",
          value: "033760",
        },
        {
          key: "POSTCODE",
          value: "BS91QX",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "ENVCO2SENSOR",
        modelTypeName: "Environment & Carbon Dioxide Sensor",
        modelTypeId: "ENVCO2SENSOR",
        id: 71,
        name: "Ei1025 Temperatuur-, Vochtigheid- & CO2-sensor",
        reference: "Ei1025",
        description: "Ei/Aico Ei1025 Temperature, Humidity & CO2 Sensor",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2021-05-04T12:03:42.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 120,
        active: true,
        isExperimental: false,
        readingTypes: [
          {
            measurementUnitId: "g/m3",
            readingTypeId: "environment.absolutehumidity.indoor",
          },
          {
            measurementUnitId: "ppm",
            readingTypeId: "environment.co2.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.feelsliketemperature.indoor",
          },
          {
            measurementUnitId: "RH",
            readingTypeId: "environment.humidity.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.temperature.indoor",
          },
        ],
        schedules: [],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: -60,
        batteryVoltage: null,
        lastSeenDate: "2023-07-18T14:03:25.701Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Silviu Nistor",
        iccid: "",
        age: 570,
        lifePercentage: 86,
      },
      lifetimeMonths: 120,
      locationName: "Bedroom 2",
      physicalSerialNumber: "002F578F",
      address: {
        uprn: "Silviu_SN_033760",
        flatIdentifier: null,
        nameNumber: "5 Knoll Court, Knoll Hill",
        street: "",
        locality: null,
        county: null,
        city: "BRISTOL",
        postcode: "BS91QX",
        country: "GB",
      },
    },
    {
      propertyId: "990fd42f-89c6-48da-8b86-e5f0d67f8851",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO-DEMO-2_CONTROL_008",
      propertyDisplayReference: "CONTROL_008",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "16a Killmore Crescent Central Bristol BS11XT GB",
      landlordId: "eabfa8b2-f703-4dfc-8a29-722dd9e646c3",
      landlordReference: "AICO-DEMO-2",
      landlordName: "Aico Demo 2",
      modelName: "Ei1000G Smartlink Gateway",
      modelTypeId: "GATEWAY",
      modelReference: "Ei1000G",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: 4,
      batteryVoltage: null,
      lastSeenDate: "2022-01-20T08:12:18.616Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "andy.smith@aico.co.uk",
      iccid: null,
      id: "04e8201a-dc57-4c3b-bcd7-a1b668a1b86b",
      name: "",
      serialNumber: "CE64ED",
      deviceSeqId: 3832,
      virtualId: null,
      locationId: "LIVINGROOM",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      installationDate: "2020-11-02T17:23:15.622Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2030-06-02T17:23:15.622Z",
      createdAt: "2021-11-04T14:07:51.734Z",
      updatedAt: "2021-11-04T14:07:51.734Z",
      hidden: false,
      modelId: 4,
      deviceId: "04e8201a-dc57-4c3b-bcd7-a1b668a1b86b",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Living Room",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "CE64ED",
      deviceIdentifiers: [
        {
          key: "originalId",
          value: "OLD_48a3a156-7183-42ab-ad48-d6486257d571",
        },
        {
          key: "originalSerial",
          value: "OLD_5B396D",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "POSTCODE",
          value: "BS11XT",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "GATEWAY",
        modelTypeName: "Gateway",
        modelTypeId: "GATEWAY",
        id: 4,
        name: "Ei1000G Smartlink Gateway",
        reference: "Ei1000G",
        description: "Gateway for alarms",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "GSM",
        syncMethodId: "PUSH",
        lifetimeMonths: 66,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Gateway Events",
            scheduleReference: "Ei1000G",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: 4,
        batteryVoltage: null,
        lastSeenDate: "2022-01-20T08:12:18.616Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "andy.smith@aico.co.uk",
        iccid: null,
        age: 1852,
        lifePercentage: 54,
      },
      lifetimeMonths: 66,
      locationName: "Living Room",
      physicalSerialNumber: "CE64ED",
      address: {
        uprn: null,
        flatIdentifier: null,
        nameNumber: "16a",
        street: "Killmore Crescent",
        locality: "Central",
        county: null,
        city: "Bristol",
        postcode: "BS11XT",
        country: "GB",
      },
    },
    {
      propertyId: "a889e326-9db4-43f0-a91f-731f11ade21a",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO_HOMELINK_DEMO_4AC",
      propertyDisplayReference: "4AC",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "4 Angela Close  TAUNTON TA14SB GB",
      landlordId: "f7d2b3bc-20a1-41d1-b52a-8c74cab27ede",
      landlordReference: "AICO_HOMELINK_DEMO",
      landlordName: "Aico HomeLINK Demo",
      modelName: "Ei1025 Temperature, Humidity & CO2 Sensor",
      modelTypeId: "ENVCO2SENSOR",
      modelReference: "Ei1025",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: -64,
      batteryVoltage: null,
      lastSeenDate: "2023-07-18T13:19:58.090Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "Tom Weisner",
      iccid: "",
      id: "05065659-d452-4807-a3fe-30c30f78101c",
      name: "Ei1025 Bedroom 2",
      serialNumber: "00307F4B",
      deviceSeqId: 212398,
      virtualId: "97272c5b-5385-4a66-a270-25b2ad2cbc38",
      locationId: "BEDROOM2",
      subLocationId: null,
      locationNickname: "H's Room",
      statusId: "ACTIVE",
      typeId: "ENV",
      parentId: null,
      installationDate: "2023-03-07T16:32:09.570Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2033-12-12T00:00:00.000Z",
      createdAt: "2023-03-07T16:32:13.766Z",
      updatedAt: "2023-03-07T16:32:13.766Z",
      hidden: false,
      modelId: 71,
      deviceId: "05065659-d452-4807-a3fe-30c30f78101c",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Bedroom 2",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "97272c5b-5385-4a66-a270-25b2ad2cbc38",
      deviceIdentifiers: [
        {
          key: "SERIALNUMBER",
          value: "00307F4B",
        },
        {
          key: "VIRTUALID",
          value: "97272c5b-5385-4a66-a270-25b2ad2cbc38",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "aicouprn",
          value: "4AC_034388",
        },
        {
          key: "aicovpid",
          value: "034388",
        },
        {
          key: "POSTCODE",
          value: "TA14SB",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "ENVCO2SENSOR",
        modelTypeName: "Environment & Carbon Dioxide Sensor",
        modelTypeId: "ENVCO2SENSOR",
        id: 71,
        name: "Ei1025 Temperatuur-, Vochtigheid- & CO2-sensor",
        reference: "Ei1025",
        description: "Ei/Aico Ei1025 Temperature, Humidity & CO2 Sensor",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2021-05-04T12:03:42.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "EIRF868",
        syncMethodId: "PUSH",
        lifetimeMonths: 120,
        active: true,
        isExperimental: false,
        readingTypes: [
          {
            measurementUnitId: "g/m3",
            readingTypeId: "environment.absolutehumidity.indoor",
          },
          {
            measurementUnitId: "ppm",
            readingTypeId: "environment.co2.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.feelsliketemperature.indoor",
          },
          {
            measurementUnitId: "RH",
            readingTypeId: "environment.humidity.indoor",
          },
          {
            measurementUnitId: "C",
            readingTypeId: "environment.temperature.indoor",
          },
        ],
        schedules: [],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: -64,
        batteryVoltage: null,
        lastSeenDate: "2023-07-18T13:19:58.090Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "Tom Weisner",
        iccid: "",
        age: 563,
        lifePercentage: 86,
      },
      lifetimeMonths: 120,
      locationName: "Bedroom 2",
      physicalSerialNumber: "00307F4B",
      address: {
        uprn: "4AC_034388",
        flatIdentifier: null,
        nameNumber: "4 Angela Close",
        street: "",
        locality: null,
        county: null,
        city: "TAUNTON",
        postcode: "TA14SB",
        country: "GB",
      },
    },
    // xxxxxxxxxxxxx
    {
      propertyId: "d93b92d3-66ee-46cb-b88e-1d167c616586",
      properyStatusId: "ACTIVE",
      propertyReference: "AICO-DEMO-1_CONTROL_009",
      propertyDisplayReference: "CONTROL_009",
      isStock: null,
      parentPropertyDisplayReference: null,
      parentPropertyReference: null,
      parentPropertyDesignationId: null,
      parentPropertyId: null,
      fullAddress: "63 Rams Lane Central Bristol BS383UT GB",
      landlordId: "c3c54bf6-4acd-4788-94e7-7b5085413f73",
      landlordReference: "AICO-DEMO-1",
      landlordName: "Aico Demo 1",
      modelName: "Ei1000G Smartlink Gateway",
      modelTypeId: "GATEWAY",
      modelReference: "Ei1000G",
      manufacturerReference: "Ei",
      modelSyncMethodId: "PUSH",
      signalStrength: 4,
      batteryVoltage: null,
      lastSeenDate: "2022-01-17T10:36:06.000Z",
      spreadingFactor: null,
      signalToNoiseRatio: null,
      gatewayCount: null,
      verificationCount: null,
      installedBy: "andy.smith@aico.co.uk",
      iccid: null,
      id: "06671f39-6f8f-4031-b7ec-3b307cc25f0b",
      name: "",
      serialNumber: "19D5B3",
      deviceSeqId: 4950,
      virtualId: null,
      locationId: "HALLWAY1",
      subLocationId: null,
      locationNickname: null,
      statusId: "ACTIVE",
      typeId: "ALARM",
      parentId: null,
      instatallationDate: "2020-11-04T15:47:05.680Z",
      uninstallationDate: null,
      lastTestedDate: null,
      replaceByDate: "2030-02-04T15:47:05.680Z",
      createdAt: "2021-11-04T13:39:41.223Z",
      updatedAt: "2024-06-25T13:20:01.433Z",
      hidden: false,
      modelId: 4,
      deviceId: "06671f39-6f8f-4031-b7ec-3b307cc25f0b",
      eventStatusId: "GOOD",
      eventStatusDescription: "Good",
      locationDescription: null,
      syncMethodId: "PUSH",
      roomName: "Hallway 1",
      subLocationName: null,
      hybridStatus: "ACTIVE",
      key: "19D5B3",
      deviceIdentifiers: [
        {
          key: "originalId",
          value: "OLD_8709456f-ca1d-46be-8eda-f665d9d08bf2",
        },
        {
          key: "originalSerial",
          value: "OLD_D6E8CD",
        },
      ],
      supportedEvents: [],
      propertyIdentifiers: [
        {
          key: "POSTCODE",
          value: "BS383UT",
        },
      ],
      scheduleStatus: [],
      model: {
        manufacturerReference: "Ei",
        manufacturerName: "Ei/Aico",
        modelTypeReference: "GATEWAY",
        modelTypeName: "Gateway",
        modelTypeId: "GATEWAY",
        id: 4,
        name: "Ei1000G Smartlink Gateway",
        reference: "Ei1000G",
        description: "Gateway for alarms",
        manufacturerId: "4775870c-74df-4f13-9ae2-638ba394db2c",
        createdAt: "2019-07-10T09:28:44.000Z",
        updatedAt: "2021-08-24T11:59:29.733Z",
        integrationNamespace: null,
        connectivityTypeId: "GSM",
        syncMethodId: "PUSH",
        lifetimeMonths: 66,
        active: true,
        isExperimental: false,
        readingTypes: [],
        schedules: [
          {
            cronExpression: "*/5 * * * *",
            granularityUnitId: "hours",
            destinationId: "ALL",
            granularityValue: 1,
            scheduleName: "Aico Gateway Events",
            scheduleReference: "Ei1000G",
            batchSize: 100,
            freshness: -60,
            readingGroupTypeName: "Event",
            readingTypes: [],
          },
        ],
      },
      activeAlerts: [],
      metadata: {
        signalStrength: 4,
        batteryVoltage: null,
        lastSeenDate: "2022-01-17T10:36:06.000Z",
        spreadingFactor: null,
        signalToNoiseRatio: null,
        gatewayCount: null,
        verificationCount: null,
        installedBy: "andy.smith@aico.co.uk",
        iccid: null,
        age: 1970,
        lifePercentage: 51,
      },
      lifetimeMonths: 66,
      locationName: "Hallway 1",
      physicalSerialNumber: "19D5B3",
      address: {
        uprn: null,
        flatIdentifier: null,
        nameNumber: "63",
        street: "Rams Lane",
        locality: "Central",
        county: null,
        city: "Bristol",
        postcode: "BS383UT",
        country: "GB",
      },
    },
  ];

  const deviceCollumns = [
    { title: "Site", field: "landlordReference" },
    { title: "Property/Site", field: "fullAddress" },
    { title: "Replace By", field: "replaceByDate" },
    { title: "Room Name", field: "roomName" },
    { title: "Install Date", field: "installationDate" },
    { title: "Last Tested Date", field: "lastTestedDate" },
    { title: "Model", field: "modelName" },
    { title: "Serial Number", field: "physicalSerialNumber" },
    { title: "Device Type", field: "modelTypeName" },
    { title: "Status", field: "active" },
  ];
</script>

<Table columns={deviceCollumns} data={device} title="table" />
